// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using web_ban_thuoc.Models;

#nullable disable

namespace web_ban_thuoc.Migrations
{
    [DbContext(typeof(LongChauDbContext))]
    [Migration("20260723035102_InitialCreateOracle")]
    partial class InitialCreateOracle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("\"NormalizedName\" IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("\"NormalizedUserName\" IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Value")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Banner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerId"));

                    b.Property<string>("BannerType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("BannerId");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("VoucherCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("VoucherDiscount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryLevel")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsFeature")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductCount")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SenderId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.DbActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NCLOB");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("DbActivityLogs");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.GoodsReceipt", b =>
                {
                    b.Property<int>("GoodsReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsReceiptId"));

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ReceiptCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("GoodsReceiptId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ReceiptCode")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("GoodsReceipts");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.GoodsReceiptLine", b =>
                {
                    b.Property<int>("GoodsReceiptLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoodsReceiptLineId"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("GoodsReceiptId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PurchaseOrderLineId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("GoodsReceiptLineId");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderLineId");

                    b.ToTable("GoodsReceiptLines");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int?>("GoodsReceiptId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProductBatchId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("SupplierName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("TransactionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductBatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.LoyaltyPointTransaction", b =>
                {
                    b.Property<int>("LoyaltyPointTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoyaltyPointTransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("LoyaltyRewardId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Points")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("LoyaltyPointTransactionId");

                    b.HasIndex("LoyaltyRewardId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId", "OrderId", "TransactionType")
                        .HasFilter("\"ORDERID\" IS NOT NULL");

                    b.ToTable("LoyaltyPointTransactions");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.LoyaltyReward", b =>
                {
                    b.Property<int>("LoyaltyRewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoyaltyRewardId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("ExpiryDays")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("MaxPerUser")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("PercentValue")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("PointsCost")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("RequiredRank")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("StockRemaining")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("LoyaltyRewardId");

                    b.ToTable("LoyaltyRewards");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Content")
                        .HasColumnType("NCLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<bool>("IsFeature")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Slug")
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("NewsId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("DistrictId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PrescriptionNote")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("VoucherCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("VoucherDiscount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("WardCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.OrderStatusHistory", b =>
                {
                    b.Property<int>("OrderStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ChangedByUserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("FromStatus")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("OrderStatusHistoryId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.PayOSWebhookEvent", b =>
                {
                    b.Property<int>("PayOSWebhookEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayOSWebhookEventId"));

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("OrderCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("PaymentSuccess")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("RawPayload")
                        .HasColumnType("NCLOB");

                    b.HasKey("PayOSWebhookEventId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("PayOSWebhookEvents");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Brand")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Contraindications")
                        .HasColumnType("NCLOB");

                    b.Property<decimal?>("CostPrice")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Dosage")
                        .HasColumnType("NCLOB");

                    b.Property<string>("IngredientUnit")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Ingredients")
                        .HasColumnType("NCLOB");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsFeature")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Origin")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Package")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("RequiresPrescription")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Sku")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Slug")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("SoldQuantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TargetUsers")
                        .HasColumnType("NCLOB");

                    b.Property<string>("Uses")
                        .HasColumnType("NCLOB");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasFilter("\"SKU\" IS NOT NULL");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.ProductBatch", b =>
                {
                    b.Property<int>("ProductBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductBatchId"));

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("GoodsReceiptLineId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ProductBatchId");

                    b.HasIndex("GoodsReceiptLineId")
                        .IsUnique()
                        .HasFilter("\"GoodsReceiptLineId\" IS NOT NULL");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("IsMain")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderId"));

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.PurchaseOrderLine", b =>
                {
                    b.Property<int>("PurchaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderLineId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("PurchaseOrderLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Rating")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentId"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("EstimatedDelivery")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("GhnOrderCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GhnPrintFormat")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GhnPrintToken")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("GhnPrintTokenExpiredAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("GhnRawResponse")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("ShippedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal?>("ShippingFee")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("TrackingCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ShipmentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.StockAdjustment", b =>
                {
                    b.Property<int>("StockAdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockAdjustmentId"));

                    b.Property<string>("AdjustmentCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("AdjustmentType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Reason")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("StockAdjustmentId");

                    b.HasIndex("AdjustmentCode")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.StockAdjustmentDetail", b =>
                {
                    b.Property<int>("StockAdjustmentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockAdjustmentDetailId"));

                    b.Property<string>("Note")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("ProductBatchId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("StockAdjustmentId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("StockAdjustmentDetailId");

                    b.HasIndex("ProductBatchId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockAdjustmentId");

                    b.ToTable("StockAdjustmentDetails");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TaxCode")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SupplierId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.UserRankInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime?>("LastNotiMailSent")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("LastRankMailSent")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("LastRankReset")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("TotalSpent6Months")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("UserId");

                    b.ToTable("UserRankInfos");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.UserVoucher", b =>
                {
                    b.Property<int>("UserVoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserVoucherId"));

                    b.Property<bool>("IsNew")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime?>("UsedDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("VoucherId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("UserVoucherId");

                    b.HasIndex("VoucherId");

                    b.HasIndex("UserId", "VoucherId")
                        .IsUnique();

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Detail")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("PercentValue")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("RequiredRank")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UsedCount")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("VoucherId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.VoucherRedemption", b =>
                {
                    b.Property<int>("VoucherRedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherRedemptionId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<bool>("IsReverted")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int>("OrderId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("VoucherId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("VoucherRedemptionId");

                    b.HasIndex("OrderId");

                    b.HasIndex("VoucherId", "OrderId")
                        .IsUnique();

                    b.ToTable("VoucherRedemptions");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.WarehouseStock", b =>
                {
                    b.Property<int>("WarehouseStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseStockId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("WarehouseStockId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("WarehouseStocks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("web_ban_thuoc.Models.CartItem", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Category", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.GoodsReceipt", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.Supplier", "Supplier")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.GoodsReceiptLine", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineId");

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrderLine");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.InventoryTransaction", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.GoodsReceipt", "GoodsReceipt")
                        .WithMany()
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.ProductBatch", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.Warehouse", "Warehouse")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("GoodsReceipt");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductBatch");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.LoyaltyPointTransaction", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.LoyaltyReward", null)
                        .WithMany()
                        .HasForeignKey("LoyaltyRewardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Order", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.OrderItem", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.OrderStatusHistory", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Order", "Order")
                        .WithMany("StatusHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Payment", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Product", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("web_ban_thuoc.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.ProductBatch", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.GoodsReceiptLine", "GoodsReceiptLine")
                        .WithOne("ProductBatch")
                        .HasForeignKey("web_ban_thuoc.Models.ProductBatch", "GoodsReceiptLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("web_ban_thuoc.Models.Warehouse", "Warehouse")
                        .WithMany("ProductBatches")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceiptLine");

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.ProductImage", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.PurchaseOrder", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.PurchaseOrderLine", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Review", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Shipment", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("web_ban_thuoc.Models.Shipment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.StockAdjustment", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.StockAdjustmentDetail", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.ProductBatch", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.StockAdjustment", "StockAdjustment")
                        .WithMany("Details")
                        .HasForeignKey("StockAdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductBatch");

                    b.Navigation("StockAdjustment");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.UserVoucher", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Voucher", "Voucher")
                        .WithMany("UserVouchers")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Voucher", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("web_ban_thuoc.Models.VoucherRedemption", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.Voucher", "Voucher")
                        .WithMany("Redemptions")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.WarehouseStock", b =>
                {
                    b.HasOne("web_ban_thuoc.Models.Product", "Product")
                        .WithMany("WarehouseStocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("web_ban_thuoc.Models.Warehouse", "Warehouse")
                        .WithMany("WarehouseStocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Category", b =>
                {
                    b.Navigation("InverseParentCategory");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.GoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.GoodsReceiptLine", b =>
                {
                    b.Navigation("ProductBatch");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("Shipment");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Product", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductBatches");

                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");

                    b.Navigation("WarehouseStocks");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.PurchaseOrder", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.StockAdjustment", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Supplier", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Voucher", b =>
                {
                    b.Navigation("Redemptions");

                    b.Navigation("UserVouchers");
                });

            modelBuilder.Entity("web_ban_thuoc.Models.Warehouse", b =>
                {
                    b.Navigation("InventoryTransactions");

                    b.Navigation("ProductBatches");

                    b.Navigation("WarehouseStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
